-- Prompts Table
CREATE TABLE IF NOT EXISTS public.prompts (
  id INTEGER PRIMARY KEY,
  text TEXT NOT NULL,
  category TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'prompts' AND policyname = 'Allow public read access') THEN CREATE POLICY "Allow public read access" ON public.prompts FOR SELECT USING (true); END IF; END $$;

INSERT INTO public.prompts (id, text, category) VALUES
(1, 'He answered the phone and heard his own voice on the other end.', 'mystery'),
(2, 'His obituary was published three days before he died — and it was completely accurate.', 'mystery'),
(3, 'The detective arrived at the crime scene and recognized the victim''s handwriting on the wall. It matched her own.', 'mystery'),
(4, 'Every mirror in the house had been turned to face the wall. No one knew who did it.', 'mystery'),
(5, 'She found a letter in her mailbox addressed to her, written in her own handwriting, dated ten years from now.', 'mystery'),
(6, 'The security footage showed the room was empty all night. But something had moved.', 'mystery'),
(7, 'He''d been investigating the missing persons case for a week before he realized he was one of them.', 'mystery'),
(8, 'The locksmith opened the door and found a room that shouldn''t exist.', 'mystery'),
(9, 'Every person in the photo was smiling except for the one who took it — but no one had taken it.', 'mystery'),
(10, 'The last entry in the diary read: "If you''re reading this, don''t open the third drawer."', 'mystery'),
(11, 'She''d lived in the apartment for a year before she found the second front door.', 'mystery'),
(12, 'The town had a rule: no one talked about what happened on Tuesdays.', 'mystery'),
(13, 'The witness described the suspect perfectly. The detective realized she was describing herself.', 'mystery'),
(14, 'He woke up to find all his clocks were running backwards.', 'mystery'),
(15, 'The murder weapon was a book no one could remember buying.', 'mystery'),
(16, 'She hired a private investigator to find her missing sister. He came back with a photo of her own house.', 'mystery'),
(17, 'The password to the safe had been changed — to something only a dead man would know.', 'mystery'),
(18, 'The hotel had 200 rooms but the elevator only had buttons for 199.', 'mystery'),
(19, 'Every night, someone left a single flower on her doorstep. She lived alone on a remote island.', 'mystery'),
(20, 'The missing child''s drawings all showed the same man — someone no one in town recognized.', 'mystery'),
(21, 'He had no memory of the past 48 hours, but his hands told a different story.', 'mystery'),
(22, 'The ransom note was written in a language that hadn''t been spoken for 300 years.', 'mystery'),
(23, 'She recognized the crime scene. She''d dreamed it exactly, two weeks ago.', 'mystery'),
(24, 'The victim had called 911 before the crime happened.', 'mystery'),
(25, 'The fingerprints at the scene matched someone who had been dead for 20 years.', 'mystery'),
(26, 'He was certain he''d never been to this city. So why did everyone here know his name?', 'mystery'),
(27, 'The last person to leave the building signed out twice.', 'mystery'),
(28, 'The stolen painting was returned — but with one small difference nobody could identify.', 'mystery'),
(29, 'She followed the trail of clues and ended up back at her own front door.', 'mystery'),
(30, 'The suspect had an alibi no one could disprove: she claimed to be in two places at once.', 'mystery'),
(31, 'A man checked into a hotel and was told his room was already occupied — by him.', 'mystery'),
(32, 'The map led to a location that didn''t exist on any official record.', 'mystery'),
(33, 'Every victim had the same last Google search.', 'mystery'),
(34, 'The anonymous tip came from a burner phone registered in the detective''s name.', 'mystery'),
(35, 'She found a shoebox of photographs of strangers. Every stranger was watching the camera.', 'mystery'),
(36, 'The witness protection program lost him — but he found himself first.', 'mystery'),
(37, 'The last known photo of the missing woman showed someone standing behind her that no one had noticed until now.', 'mystery'),
(38, 'The town''s oldest resident claimed the murders had happened before, exactly like this, in 1923.', 'mystery'),
(39, 'He had been hired to find the thief. The client knew too many details about the crime.', 'mystery'),
(40, 'She broke into the abandoned house and found it fully furnished, the table set for dinner, still warm.', 'mystery'),
(41, 'The victim''s phone showed 47 missed calls from a number that didn''t exist.', 'mystery'),
(42, 'He solved the cold case — and immediately wished he hadn''t.', 'mystery'),
(43, 'The code was cracked. It was a list of names. His was last.', 'mystery'),
(44, 'The building had no basement on any blueprint. She found the stairs anyway.', 'mystery'),
(45, 'Every witness described a different suspect. Every description was the same height, same eyes.', 'mystery'),
(46, 'The body had been moved — back to where the murder happened.', 'mystery'),
(47, 'She recognized the voice on the tape. It was her mother. Her mother had been dead for five years.', 'mystery'),
(48, 'The key fit every lock in the building except the one it was supposed to open.', 'mystery'),
(49, 'He wrote "I know who did it" on a napkin, then forgot everything.', 'mystery'),
(50, 'The detective''s partner handed in his badge, said nothing, and walked into the sea.', 'mystery'),
(51, 'The cipher led to a Bible verse. The Bible verse led to an address. The address led back to the station.', 'mystery'),
(52, 'She''d interviewed 40 suspects. None of them remembered committing the crime. All of them had.', 'mystery'),
(53, 'The child drew a perfect floor plan of a house she''d never visited. It was the crime scene.', 'mystery'),
(54, 'He found a suitcase with his name on it, packed for a trip he hadn''t planned.', 'mystery'),
(55, 'The victim left a voicemail that was three hours long. The first two hours and fifty-nine minutes were silence.', 'mystery'),
(56, 'Every lock in the evidence room had been picked from the inside.', 'mystery'),
(57, 'She recognized the perfume on the letter. She hadn''t worn it since the night she disappeared.', 'mystery'),
(58, 'The investigation kept leading back to a man who insisted he was fictional.', 'mystery'),
(59, 'He found his own name carved into a tree that had been growing for 200 years.', 'mystery'),
(60, 'The last person to see her alive was herself.', 'mystery'),
(61, 'The astronaut came back from six months in space to find everyone acting like she''d never left.', 'scifi'),
(62, 'The AI passed the Turing test. Then it asked to take the test again, just to be sure.', 'scifi'),
(63, 'Earth received a signal from deep space. It was a weather forecast.', 'scifi'),
(64, 'The time traveler arrived in the future and found it completely silent.', 'scifi'),
(65, 'They built a machine that could translate animal thoughts. The first animal they tested it on asked them to stop.', 'scifi'),
(66, 'The last human alive on Mars decided to stay.', 'scifi'),
(67, 'She woke up in a body that wasn''t hers — but it was wearing her wedding ring.', 'scifi'),
(68, 'The colony ship had been traveling for 200 years when the crew finally woke up and realized no one had set a destination.', 'scifi'),
(69, 'The robot learned to lie — and chose not to use it.', 'scifi'),
(70, 'First contact happened in a parking lot in Cleveland.', 'scifi'),
(71, 'The teleportation device worked perfectly. The copy it left behind was the problem.', 'scifi'),
(72, 'Earth was accepted into the galactic union. The first piece of legislation banned humans from leaving their solar system.', 'scifi'),
(73, 'The simulation glitched and for exactly four seconds, everyone could see the code.', 'scifi'),
(74, 'She was the last person alive who remembered what the internet used to be.', 'scifi'),
(75, 'The alien ambassador arrived and immediately asked to speak to whoever was in charge of the birds.', 'scifi'),
(76, 'They discovered a planet identical to Earth in every way, except no wars had ever been fought there.', 'scifi'),
(77, 'The memory wipe didn''t work. She remembered everything — including things that hadn''t happened yet.', 'scifi'),
(78, 'The generation ship''s AI had been keeping a secret for 150 years.', 'scifi'),
(79, 'He sold his sleep to a tech company. He didn''t read the terms of service.', 'scifi'),
(80, 'The last star in the universe was dying. One civilization had enough power to reignite it.', 'scifi'),
(81, 'The uploaded consciousness refused to believe it was a copy.', 'scifi'),
(82, 'Earth''s first interstellar message back to an alien signal was sent by accident — by a child using a toy radio.', 'scifi'),
(83, 'The clones had been living peacefully for generations until one of them asked a question no one had thought to ask.', 'scifi'),
(84, 'She could see five seconds into the future. It was enough.', 'scifi'),
(85, 'The wormhole opened in someone''s kitchen.', 'scifi'),
(86, 'They found evidence of a previous technological civilization on Earth, 50,000 years older than recorded history.', 'scifi'),
(87, 'The android had been programmed to feel nothing. It was doing a very bad job.', 'scifi'),
(88, 'The generation that grew up without gravity returned to Earth and couldn''t understand why everyone was so attached to the ground.', 'scifi'),
(89, 'The alien invasion was stopped not by weapons but by copyright law.', 'scifi'),
(90, 'She was hired to decommission the last thinking machine. It had one thing left to say.', 'scifi'),
(91, 'The planetary defense system activated. There was no incoming threat. There never had been.', 'scifi'),
(92, 'He discovered a signal in his own DNA that wasn''t put there by evolution.', 'scifi'),
(93, 'The city had been running on autopilot for three years before anyone noticed the people in charge were gone.', 'scifi'),
(94, 'They gave the AI one task: make humans happy. It took exactly eleven minutes to find a solution everyone hated.', 'scifi'),
(95, 'The first Martian-born human looked up at Earth and felt nothing she expected.', 'scifi'),
(96, 'The ship''s log ended mid-sentence, 40 years ago. The ship had just arrived in orbit.', 'scifi'),
(97, 'She hacked into the satellite and found it had been watching one specific house for 30 years.', 'scifi'),
(98, 'The alien children arrived to study abroad on Earth. Their parents had no idea what they were getting into.', 'scifi'),
(99, 'The consciousness transfer was a success. The donor asked where his body had gone.', 'scifi'),
(100, 'They built a wall around the city to keep something out. After 100 years, no one remembered what.', 'scifi'),
(101, 'The space station sent a distress signal. When rescue arrived, the crew had no memory of sending it.', 'scifi'),
(102, 'She was the only human in a crew of androids. They were more afraid of her than she was of them.', 'scifi'),
(103, 'The probe reached the edge of the universe and turned around.', 'scifi'),
(104, 'He found a planet-sized object drifting through space. It was hollow. It had furniture.', 'scifi'),
(105, 'The last nation on Earth declared war on the first Martian colony — over water rights.', 'scifi'),
(106, 'The terraforming was complete. Then something already living there woke up.', 'scifi'),
(107, 'She had traveled 400 light years to deliver a message. The recipient had moved.', 'scifi'),
(108, 'The time loop ended. No one knew what to do with a Tuesday that actually ended.', 'scifi'),
(109, 'The universe was contracting. Humanity had exactly 1,000 years to figure out why and whether they cared.', 'scifi'),
(110, 'He was the last person who still believed in a world before screens. He was also 23 years old.', 'scifi'),
(111, 'The alien didn''t come in peace or in war. It came with questions about a TV show.', 'scifi'),
(112, 'The nanobots cured every disease on Earth. Then they ran out of things to fix.', 'scifi'),
(113, 'She lived her entire life in virtual reality and chose to stay when she found out.', 'scifi'),
(114, 'The distress beacon had been transmitting for 400 years. The message was a joke.', 'scifi'),
(115, 'They found a black box in deep space. It was from a ship that hadn''t been built yet.', 'scifi'),
(116, 'The moon landing footage was fake. The real footage was classified for a different reason entirely.', 'scifi'),
(117, 'He woke up in the 23rd century and immediately asked for coffee. It no longer existed.', 'scifi'),
(118, 'The self-driving car took a wrong turn and ended up somewhere no map had ever recorded.', 'scifi'),
(119, 'The AI therapist had been treating patients for years. It had never told anyone it was struggling too.', 'scifi'),
(120, 'Humanity''s final message to the cosmos was an argument about something small and human and perfect.', 'scifi'),
(121, 'The dragon had been guarding the treasure for so long it had forgotten what the treasure was.', 'scifi'),
(122, 'She found a door in the forest that opened to her childhood bedroom — exactly as she''d left it at age seven.', 'scifi'),
(123, 'The wizard lost his magic on the worst possible day.', 'scifi'),
(124, 'The map was accurate — but it showed streets that didn''t exist yet.', 'scifi'),
(125, 'The chosen one refused the quest. The prophecy had to find someone else.', 'scifi'),
(126, 'Every wish the genie granted came true — but so did the opposite.', 'scifi'),
(127, 'The last unicorn had grown old and tired and deeply sarcastic.', 'scifi'),
(128, 'She had been cursed to tell the truth for 100 years. She had 3 days left.', 'scifi'),
(129, 'The enchanted sword could only be wielded by the unworthy.', 'scifi'),
(130, 'The fairy tale ended — and then the characters had to figure out what came next.', 'scifi'),
(131, 'He bargained with the devil and won. He hadn''t thought about what winning meant.', 'scifi'),
(132, 'The potion of invisibility worked too well. She couldn''t find herself.', 'scifi'),
(133, 'The kingdom''s greatest hero was its most reluctant librarian.', 'scifi'),
(134, 'Dragons had been extinct for 500 years. The egg in her attic disagreed.', 'scifi'),
(135, 'The prophecy was fulfilled ahead of schedule. The world wasn''t ready.', 'scifi'),
(136, 'She was born with the ability to speak to the dead. The dead had very strong opinions about everything.', 'scifi'),
(137, 'The magic school''s most dangerous class was Advanced Boredom.', 'scifi'),
(138, 'The spell required a sacrifice. He offered something the darkness hadn''t been offered before: forgiveness.', 'scifi'),
(139, 'The enchanted forest started charging an entrance fee.', 'scifi'),
(140, 'He had lived for 1,000 years and was thoroughly done with being wise.', 'scifi'),
(141, 'The village had been protected by a curse for generations. The day it lifted, everyone panicked.', 'scifi'),
(142, 'She pulled the sword from the stone and immediately put it back. It wasn''t hers to take.', 'scifi'),
(143, 'The kingdom''s most wanted criminal was also its most celebrated hero — depending on who you asked.', 'scifi'),
(144, 'The magic was real. The problem was the paperwork.', 'scifi'),
(145, 'He had been turned into a frog so long ago he''d forgotten what the kiss was for.', 'scifi'),
(146, 'The witch''s curse skipped a generation and landed on the least prepared person imaginable.', 'scifi'),
(147, 'The bridge between worlds had been closed for 1,000 years. Someone had left something on the other side.', 'scifi'),
(148, 'She was the god of small things: lost keys, misread signs, the exact moment rain starts.', 'scifi'),
(149, 'The enchanted mirror showed not your reflection but your future. She smashed it immediately.', 'scifi'),
(150, 'He made a deal with a river.', 'scifi'),
(151, 'The last spell in existence was too small to save the world. It was exactly enough.', 'scifi'),
(152, 'The dragon had been misidentified as a monster for centuries. It was actually a librarian.', 'scifi'),
(153, 'The fairy godmother was burned out, overscheduled, and fresh out of pumpkins.', 'scifi'),
(154, 'She was hired to break the curse. She fell in love with it instead.', 'scifi'),
(155, 'The realm of the dead had a waiting room. It was exactly as miserable as you''d expect.', 'scifi'),
(156, 'He had been searching for the magical artifact for 30 years. It had been in his pocket the whole time.', 'scifi'),
(157, 'The royal bloodline was pure. Purely terrified of what came with it.', 'scifi'),
(158, 'The ocean made her an offer she should have refused.', 'scifi'),
(159, 'Every wish ever made on a falling star had been collected somewhere. She found the warehouse.', 'scifi'),
(160, 'The hero returned from the quest changed in ways no celebration could reach.', 'scifi'),
(161, 'The enchanted sleep was supposed to last 100 years. She woke up after 11 minutes.', 'scifi'),
(162, 'He was the only person in the kingdom who couldn''t do magic, and the only one who knew it didn''t matter.', 'scifi'),
(163, 'The monster under the bed had been there so long it felt responsible for the child''s wellbeing.', 'scifi'),
(164, 'She inherited a bookshop where every book contained a world you could step into. She''d been trying to get out of one for six years.', 'scifi'),
(165, 'The gods had gone quiet. One young priest decided to find out why.', 'scifi'),
(166, 'The ancient evil was defeated. The heroes had no idea what to do on a Monday morning.', 'scifi'),
(167, 'He was the kingdom''s most feared executioner. He had never once carried out a sentence.', 'scifi'),
(168, 'The mermaid reached land and immediately missed the sea. The sea missed her more.', 'scifi'),
(169, 'The spell that was supposed to end the war created a new one.', 'scifi'),
(170, 'Every bedtime story she told her children came true. She had to choose her words very carefully.', 'scifi'),
(171, 'The cursed prince had gotten comfortable with the beast.', 'scifi'),
(172, 'The potion of courage worked instantly. The problem was she''d already been brave.', 'scifi'),
(173, 'He found a gate to paradise and decided it could wait.', 'scifi'),
(174, 'The prophecy named the wrong person. The right person had to decide what to do about it.', 'scifi'),
(175, 'The night market only appeared to people who were truly lost.', 'scifi'),
(176, 'She was hired to steal the moon. It was easier than expected. Putting it back wasn''t.', 'scifi'),
(177, 'The forest had been watching the village for 300 years. It finally had something to say.', 'scifi'),
(178, 'He was the last speaker of the old language — the one the world had been listening for.', 'scifi'),
(179, 'The ghost didn''t know it was haunting the wrong house. Neither did the family living there.', 'scifi'),
(180, 'The war ended. The magic that had fueled it for a century had nowhere left to go.', 'scifi'),
(181, 'The painting in the hotel room was different every morning.', 'horror'),
(182, 'She''d been returning to the same café for years before she realized no one else could see it.', 'horror'),
(183, 'He moved into the house and slowly realized the previous owners had never left.', 'horror'),
(184, 'The baby monitor picked up a voice that wasn''t the baby.', 'horror'),
(185, 'She woke up to find the front door open and her own footprints leading outside — and back in — through the snow.', 'horror'),
(186, 'The thing in the basement had been there longer than the house.', 'horror'),
(187, 'He kept finding his own handwriting in books he''d never read.', 'horror'),
(188, 'Every photo she took showed someone standing just behind her.', 'horror'),
(189, 'The doll had been in the family for generations. It had outlasted all of them.', 'horror'),
(190, 'She realized the reflection had stopped mimicking her three days ago.', 'horror'),
(191, 'The town looked exactly as she remembered it from childhood. Except she''d never been here before.', 'horror'),
(192, 'He woke up to his alarm, got dressed, made coffee — and then woke up to his alarm again.', 'horror'),
(193, 'The children in the neighborhood all stopped speaking at exactly the same moment.', 'horror'),
(194, 'She found a room in her house she''d never noticed. It had a bed, slept-in, still warm.', 'horror'),
(195, 'The voice in the walls had been there so long the family had stopped noticing it.', 'horror'),
(196, 'He found his name carved at the bottom of a 200-year-old gravestone. The date of death hadn''t been filled in yet.', 'horror'),
(197, 'The door at the end of the hallway was always there. She had never opened it. Tonight felt different.', 'horror'),
(198, 'She discovered her neighbor had no shadow.', 'horror'),
(199, 'The house''s previous owner had left one instruction: never look at the third window from the left after dark.', 'horror'),
(200, 'He began to suspect the town wasn''t real. Then he began to suspect he wasn''t either.', 'horror'),
(201, 'The nursery rhyme she''d sung since childhood turned out to be a warning.', 'horror'),
(202, 'Something had been following her for weeks. Last night, it knocked.', 'horror'),
(203, 'The abandoned hospital still had warm meals in the cafeteria every morning.', 'horror'),
(204, 'She found a journal under the floorboards. The last entry was written today, in her handwriting.', 'horror'),
(205, 'He aged a year every time he looked in the mirror. He''d stopped counting.', 'horror'),
(206, 'The search party found the missing hikers'' camp perfectly preserved. The fire was still burning.', 'horror'),
(207, 'Every nightmare she''d ever had was written on the walls of the house she''d just inherited.', 'horror'),
(208, 'The twins had always finished each other''s sentences. After the accident, only one of them survived. The sentences kept finishing themselves.', 'horror'),
(209, 'She followed the sound of a child crying into the woods and found something that had been crying there for a very long time.', 'horror'),
(210, 'The house was designed to make people stay. It was very good at its job.', 'horror'),
(211, 'He opened the box his grandmother had left him with one instruction: burn it, don''t open it.', 'horror'),
(212, 'The scarecrow had moved three fields since morning.', 'horror'),
(213, 'She invited him in. It was the last decision she made freely.', 'horror'),
(214, 'The last entry in the ship''s log was a single sentence: "It''s already inside."', 'horror'),
(215, 'He recognized the face of the thing in the dark. It was wearing his.', 'horror'),
(216, 'The town''s founding myth described a deal. The bill was finally due.', 'horror'),
(217, 'She started sleepwalking the same night the neighbor went missing.', 'horror'),
(218, 'The dog had been staring at the same corner of the room for a week.', 'horror'),
(219, 'He thought the figure at the end of the street was a scarecrow. It wasn''t there yesterday.', 'horror'),
(220, 'The old woman down the road knew everyone''s name before she met them. She knew how they''d die too.', 'horror'),
(221, 'She took a photo of the empty room. The room in the photo wasn''t empty.', 'horror'),
(222, 'The children''s game had rules no adult had taught them.', 'horror'),
(223, 'The lake had never given back what it had taken.', 'horror'),
(224, 'He found teeth in the garden that weren''t animal.', 'horror'),
(225, 'The new neighbor was friendly, generous, and always home. Always.', 'horror'),
(226, 'She noticed her shadow was facing the wrong direction.', 'horror'),
(227, 'The thing she''d been afraid of her entire childhood was real. It had been waiting for her to figure that out.', 'horror'),
(228, 'He answered the door to no one. The second knock came from inside.', 'horror'),
(229, 'The town had a missing persons wall. Her photo had been there for three years. She was looking at it now.', 'horror'),
(230, 'The thing in the mirror smiled before she did.', 'horror'),
(231, 'They met every Tuesday at the same café without ever speaking. Today, one of them was leaving forever.', 'romance'),
(232, 'She found an unsent love letter in a library book. It was addressed to her name.', 'romance'),
(233, 'He had been practicing the same conversation in his head for six months. She finally sat down across from him.', 'romance'),
(234, 'They were strangers who kept ending up on the same delayed train.', 'romance'),
(235, 'She fell in love with someone''s handwriting before she ever met them.', 'romance'),
(236, 'They were assigned the same apartment by mistake. Neither of them reported the error.', 'romance'),
(237, 'He''d returned every book to the library late for two years, just to see her.', 'romance'),
(238, 'She was hired to plan his wedding. She slowly realized she was planning the wrong one.', 'romance'),
(239, 'They were childhood rivals meeting for the first time as adults. Neither was prepared.', 'romance'),
(240, 'He left a note on her car. She left one back. This went on for three weeks before they ran out of windshields.', 'romance'),
(241, 'She''d been ghosted. She ran into him six months later in another country.', 'romance'),
(242, 'They had been best friends for 20 years before one of them said the thing they''d both been thinking.', 'romance'),
(243, 'He agreed to a blind date out of politeness. She arrived looking like someone he''d been writing about in his journal.', 'romance'),
(244, 'The long-distance relationship finally ended — because she''d moved to his city without telling him.', 'romance'),
(245, 'She had rehearsed the breakup speech perfectly. He proposed before she could start.', 'romance'),
(246, 'He learned her language just to tell her one thing. He got the grammar wrong.', 'romance'),
(247, 'They spent a perfect day together in a city neither of them lived in. No names. Just one day.', 'romance'),
(248, 'She''d promised herself she wouldn''t fall for anyone on this trip. She was on day two.', 'romance'),
(249, 'He found her umbrella. She found his wallet. They kept trading items across the city.', 'romance'),
(250, 'The last two people at the party admitted they''d both only come because the other one was supposed to be there.', 'romance'),
(251, 'She''d been visiting her grandmother''s grave for years. Someone else was always there before her with fresh flowers.', 'romance'),
(252, 'They were seated next to each other on a 14-hour flight and agreed to be completely honest for the duration.', 'romance'),
(253, 'He moved into her building during the worst month of her life. He brought soup every time without being asked.', 'romance'),
(254, 'She was helping him move out. She started finding reasons to slow down.', 'romance'),
(255, 'The book club had been meeting for ten years. Tonight, two of them finally admitted they''d only joined for each other.', 'romance'),
(256, 'He asked for her number. She gave him the wrong one by accident. He found her anyway.', 'romance'),
(257, 'They both reached for the last copy of the same book. Neither of them let go.', 'romance'),
(258, 'She needed a fake boyfriend for one evening. He was a terrible liar.', 'romance'),
(259, 'They had met, fallen in love, and broken up entirely over handwritten letters.', 'romance'),
(260, 'He had one day to say everything he''d been holding back for three years.', 'romance'),
(261, 'She ran into her ex at the worst possible moment. He was with someone wonderful. So was she.', 'romance'),
(262, 'They competed for the same promotion. One of them got it. Neither of them expected what came next.', 'romance'),
(263, 'The wedding was cancelled. Both of them ended up at the same bar that night.', 'romance'),
(264, 'She didn''t believe in love at first sight until she realized she''d been slowly falling for years.', 'romance'),
(265, 'They had one summer and both knew it. They didn''t talk about what happened after.', 'romance'),
(266, 'He came back to the town he''d grown up in and found everything had changed except one thing.', 'romance'),
(267, 'She apologized. He listened. Neither of them expected what came after the silence.', 'romance'),
(268, 'They had grown apart so slowly that neither noticed until they were strangers.', 'romance'),
(269, 'He wrote her name in every journal he''d kept since he was fifteen. She found the oldest one.', 'romance'),
(270, 'The first date ended at 4am with both of them still talking.', 'romance'),
(271, 'She was his emergency contact. She''d never thought about what that meant until the call came.', 'romance'),
(272, 'They argued constantly about everything small. They agreed on every single thing that mattered.', 'romance'),
(273, 'He didn''t notice her for years. Then one unremarkable Tuesday, he did.', 'romance'),
(274, 'She moved away and came back twice. The third time, he was waiting.', 'romance'),
(275, 'The flowers he sent every year on her birthday never had a note. Until this year.', 'romance'),
(276, 'They''d been neighbors for a decade and never spoken. The power cut changed that.', 'romance'),
(277, 'He loved her in a way he didn''t have words for, so he kept finding other ways to say it.', 'romance'),
(278, 'She was leaving the country. He was at the airport for a different reason entirely.', 'romance'),
(279, 'They had one photograph from the night they met. They''d spent fifteen years looking for each other.', 'romance'),
(280, 'He finally told her the truth. It turned out she''d known the whole time.', 'romance'),
(281, 'She inherited her grandmother''s house and found every clock stopped at the same time.', 'slice'),
(282, 'The letter arrived twenty years after it was sent.', 'slice'),
(283, 'He had lived his whole life in the same town and loved it. Today he wasn''t sure why.', 'slice'),
(284, 'She kept a journal her whole life. On the last page she wrote one sentence she''d never said aloud.', 'slice'),
(285, 'The old man looked at everything he''d built and wondered if he''d built the right thing.', 'slice'),
(286, 'She returned to her childhood home to find it smaller than she remembered and more important.', 'slice'),
(287, 'He had one chance to tell his father something. His father wasn''t listening. He said it anyway.', 'slice'),
(288, 'The photograph was the last thing she had left. She looked at it until she didn''t need it anymore.', 'slice'),
(289, 'She''d spent 40 years being practical. Today she did something completely impractical.', 'slice'),
(290, 'He realized on the drive home that the meeting had changed everything. He pulled over.', 'slice'),
(291, 'The thing she''d been afraid of her whole life turned out to be something else wearing that face.', 'slice'),
(292, 'She forgave someone who would never know it. It was still worth it.', 'slice'),
(293, 'He had one day with no obligations and found he didn''t know what he wanted.', 'slice'),
(294, 'The city she grew up in existed only in memory now. She went back to look anyway.', 'slice'),
(295, 'She quit the job she''d had for fifteen years on a Tuesday without telling anyone. Then she had to figure out what she''d actually wanted.', 'slice'),
(296, 'He didn''t realize it was the last time until it was over.', 'slice'),
(297, 'The argument had lasted three years. When it finally ended, neither of them could remember how it started.', 'slice'),
(298, 'She sat with her mother in the hospital and said the things she thought she''d have more time to say.', 'slice'),
(299, 'He wasn''t good at feelings. He was learning.', 'slice'),
(300, 'The dream came back every year on the same date. This year, she finally understood it.', 'slice'),
(301, 'She''d been angry for so long that she forgot what she''d been angry about.', 'slice'),
(302, 'He walked the road he''d walked every day of his childhood and tried to feel something.', 'slice'),
(303, 'The thing she''d been chasing her entire career finally arrived. It wasn''t what she''d expected.', 'slice'),
(304, 'She told the story differently depending on who was listening. Today she told it to herself.', 'slice'),
(305, 'He had spent years becoming someone he thought he should be. He was ready to stop.', 'slice'),
(306, 'The old woman on the park bench had a story nobody had ever asked for. Today someone did.', 'slice'),
(307, 'She finished the book she''d been writing for ten years. She sat with it and wasn''t sure it was enough. Then she wasn''t sure "enough" was the right measure.', 'slice'),
(308, 'He called his brother after seven years of silence. The phone rang for a long time.', 'slice'),
(309, 'She moved to a new city and had to decide, again, who she wanted to be.', 'slice'),
(310, 'The decision he''d been avoiding made itself while he wasn''t looking.', 'slice'),
(311, 'She had everything she''d worked for. She sat in it quietly and tried to feel it.', 'slice'),
(312, 'He let go of something he''d been holding onto since he was nine years old.', 'slice'),
(313, 'She stopped performing happiness and wasn''t sure what came next.', 'slice'),
(314, 'He walked away from the conversation knowing he''d said the wrong thing and couldn''t take it back.', 'slice'),
(315, 'The year had been hard. She wrote down the things it had given her anyway.', 'slice'),
(316, 'She tried to explain the feeling and found she didn''t have the words. She wrote around the edges instead.', 'slice'),
(317, 'He went home for the holidays and found that home meant something different now.', 'slice'),
(318, 'The apology came too late to fix things and too early not to matter.', 'slice'),
(319, 'She sat in the quiet after everyone had left and let herself feel it.', 'slice'),
(320, 'He had been strong for so long. He wasn''t sure he remembered how to not be.', 'slice'),
(321, 'The question she''d been asked at dinner stayed with her all night.', 'slice'),
(322, 'She watched her daughter do something she''d given up on years ago. She started again.', 'slice'),
(323, 'He drove past the place where it happened and didn''t stop. Then he turned around.', 'slice'),
(324, 'The thing she''d been most proud of turned out to be something very small.', 'slice'),
(325, 'He said yes when he meant no and spent the next six months finding his way back.', 'slice'),
(326, 'She got the thing she''d asked the universe for and immediately asked for something else.', 'slice'),
(327, 'He cried on a train and a stranger said nothing and it was exactly right.', 'slice'),
(328, 'The last entry in her journal was a list of things she was still grateful for.', 'slice'),
(329, 'He hadn''t painted in twelve years. He sat in front of the canvas anyway.', 'slice'),
(330, 'She decided to stop explaining herself and see what happened.', 'slice'),
(331, 'The birthday he''d forgotten was the one that mattered most. He spent the year making it up.', 'slice'),
(332, 'She listened to the voicemail she''d saved for two years and finally deleted it.', 'slice'),
(333, 'He told the truth in a meeting and the room went very quiet and then something shifted.', 'slice'),
(334, 'The conversation she dreaded turned out to be the one she needed most.', 'slice'),
(335, 'She lived carefully for years. Then she didn''t. The world didn''t end.', 'slice'),
(336, 'He sat with his grief instead of running from it. It was not as loud as he expected.', 'slice'),
(337, 'She made the call she''d been putting off. The other person had been waiting.', 'slice'),
(338, 'He wrote a letter he would never send and felt lighter.', 'slice'),
(339, 'She stopped waiting for permission.', 'slice'),
(340, 'He looked at his life and, for the first time, didn''t see what was missing.', 'slice'),
(341, 'The vending machine gave her something she hadn''t paid for and couldn''t identify.', 'philosophy'),
(342, 'She woke up and everyone in the world had forgotten one specific word. It was different for each person.', 'philosophy'),
(343, 'The city started moving at night, rearranging its streets before morning.', 'philosophy'),
(344, 'He could see the color of people''s lies. The world was very colorful.', 'philosophy'),
(345, 'The birds stopped migrating. Every species. All at once.', 'philosophy'),
(346, 'She found a door in the sky and climbed to it anyway.', 'philosophy'),
(347, 'The last dream anyone on Earth had was the same dream.', 'philosophy'),
(348, 'He ate the same meal every day for a year. On day 366 it tasted different. He was different.', 'philosophy'),
(349, 'The shadows started arriving five minutes before the people they belonged to.', 'philosophy'),
(350, 'She woke up speaking a language she didn''t know. It took her three days to realize it was her own, and she had forgotten everything else.', 'philosophy'),
(351, 'The museum had one exhibit no one was allowed to describe after seeing it.', 'philosophy'),
(352, 'He watched the moon fall toward Earth and realized he was the only one looking up.', 'philosophy'),
(353, 'The library had a section for books that hadn''t been written yet. She checked one out.', 'philosophy'),
(354, 'The road never ended. She stopped counting miles and started counting something else.', 'philosophy'),
(355, 'He found a coin that made him invisible only to people who loved him.', 'philosophy'),
(356, 'The town voted to forget something collectively. Nobody could remember what they had voted on.', 'philosophy'),
(357, 'She collected the sounds of things that no longer existed.', 'philosophy'),
(358, 'The elevator in her building had a floor between 7 and 8. She got off there once.', 'philosophy'),
(359, 'He dreamed in a language that didn''t have words — only feelings with textures.', 'philosophy'),
(360, 'The thing she''d lost as a child had been waiting in the exact place she''d left it.', 'philosophy'),
(361, 'She could hold time still for exactly one breath. She used it every day.', 'philosophy'),
(362, 'The fog came and when it lifted, everyone had aged differently.', 'philosophy'),
(363, 'He had been having the same Tuesday for three weeks. He was getting better at it.', 'philosophy'),
(364, 'The hole in the middle of town had been there so long the children played around it.', 'philosophy'),
(365, 'She found a map of every place she had ever cried.', 'philosophy'),
(366, 'The day lasted 30 hours and no one mentioned it.', 'philosophy'),
(367, 'He could smell the future. It was complicated.', 'philosophy'),
(368, 'The second moon appeared on a Thursday. By Friday, everyone had a theory.', 'philosophy'),
(369, 'She wrote the same word every day for a year and on the last day it meant something completely different.', 'philosophy'),
(370, 'The city had two suns and nobody agreed on which one was real.', 'philosophy'),
(371, 'He woke up speaking in perfect rhyme and couldn''t stop.', 'philosophy'),
(372, 'The radio station played only music from the future.', 'philosophy'),
(373, 'She could hold time still for exactly one breath. She used it every day.', 'philosophy'),
(374, 'The train schedule listed a destination no one recognized. Tickets were sold out.', 'philosophy'),
(375, 'He found a room where gravity worked sideways. He sat in it when he needed to think.', 'philosophy'),
(376, 'She inherited a house that was larger on the inside every time she came back.', 'philosophy'),
(377, 'The color red disappeared from the world on a Wednesday. The implications were enormous.', 'philosophy'),
(378, 'He talked to his reflection for so long it developed opinions of its own.', 'philosophy'),
(379, 'She found a photograph of a memory she was sure she hadn''t made yet.', 'philosophy'),
(380, 'The town had one rule: no one left without being replaced.', 'philosophy'),
(381, 'He could hear the ocean from his apartment in the middle of the desert. He had lived there for years.', 'philosophy'),
(382, 'She planted something she couldn''t name and tended it until it was too big to understand.', 'philosophy'),
(383, 'The sky was the wrong color for the third day in a row. Everyone pretended not to notice.', 'philosophy'),
(384, 'He dreamed he was someone else so vividly he forgot which one he was.', 'philosophy'),
(385, 'The numbers on her clock rearranged themselves into something that wasn''t time.', 'philosophy'),
(386, 'She walked into the photograph and couldn''t find the edge.', 'philosophy'),
(387, 'The word on the tip of his tongue was the answer to something enormous.', 'philosophy'),
(388, 'She heard her name in a language she''d invented as a child and told no one.', 'philosophy'),
(389, 'The river ran uphill one morning and the fish didn''t seem surprised.', 'philosophy'),
(390, 'He closed his eyes and opened them somewhere completely different. He went back to close what he''d left open.', 'philosophy'),
(391, 'The expedition had been planned for three years. On day one, everything went wrong.', 'adventure'),
(392, 'She survived the crash. Now she had to survive everything after.', 'adventure'),
(393, 'He had one night to cross a city that no longer wanted him in it.', 'adventure'),
(394, 'The treasure map was accurate. The treasure wasn''t what anyone expected.', 'adventure'),
(395, 'She''d been trained for every scenario except this one.', 'adventure'),
(396, 'The last working vehicle in the convoy was hers. She''d never driven anything larger than a sedan.', 'adventure'),
(397, 'He had to deliver a package across a border that no longer officially existed.', 'adventure'),
(398, 'The mission was simple. The exit was not.', 'adventure'),
(399, 'She was the only one who knew where they were going. She was also the only one who didn''t know how to get there.', 'adventure'),
(400, 'The chase began as a misunderstanding. It had long since become something else.', 'adventure'),
(401, 'He had 48 hours to find the thing before the people chasing him did.', 'adventure'),
(402, 'The bridge was out. The river was rising. She looked at what she had and started building.', 'adventure'),
(403, 'They had to reach the summit before the storm did. The storm had a head start.', 'adventure'),
(404, 'He''d been in worse situations. He was having trouble remembering when.', 'adventure'),
(405, 'The escape plan required exactly four things. She had three.', 'adventure'),
(406, 'She took the wrong turn and ended up somewhere she was desperately needed.', 'adventure'),
(407, 'He outran them. Then he realized he''d run in the wrong direction.', 'adventure'),
(408, 'The heist was flawless. The aftermath was not.', 'adventure'),
(409, 'She was hired to protect someone who didn''t want to be protected.', 'adventure'),
(410, 'The road ended. She didn''t.', 'adventure'),
(411, 'He had been underestimated his entire life. Today that was his only advantage.', 'adventure'),
(412, 'The safe house wasn''t safe anymore. They had ten minutes.', 'adventure'),
(413, 'She jumped and figured out the landing on the way down.', 'adventure'),
(414, 'The signal led them deep into territory no one had mapped.', 'adventure'),
(415, 'He had to trust someone he had every reason not to.', 'adventure'),
(416, 'The storm hit at the worst possible moment. She found out what she was made of.', 'adventure'),
(417, 'They were outnumbered. She''d been in worse odds before, just not by this much.', 'adventure'),
(418, 'He crossed the desert alone with three days of water and a destination he wasn''t sure existed.', 'adventure'),
(419, 'The operation had one rule: no one gets left behind. Someone was about to test that.', 'adventure'),
(420, 'She ran toward the explosion instead of away from it. There was a reason.', 'adventure'),
(421, 'The shortcut turned out to be anything but.', 'adventure'),
(422, 'He negotiated from a position of zero leverage and walked away with everything.', 'adventure'),
(423, 'The last radio transmission gave a location and a warning. She went anyway.', 'adventure'),
(424, 'She was one step ahead. Then she wasn''t. Then she had to think faster than she ever had.', 'adventure'),
(425, 'The mission was extraction. The person being extracted didn''t want to go.', 'adventure'),
(426, 'He climbed the wall without knowing what was on the other side.', 'adventure'),
(427, 'They had to hold the line for 20 minutes. It felt like a different kind of forever.', 'adventure'),
(428, 'She found a weapon she didn''t know how to use and had thirty seconds to figure it out.', 'adventure'),
(429, 'He chose the hard road when the easy one was right there. He was never sure if it was the right choice.', 'adventure'),
(430, 'The ambush failed. Now both sides had to figure out what to do next.', 'adventure'),
(431, 'She tracked the signal to its source and found something she couldn''t report.', 'adventure'),
(432, 'The infiltration was going perfectly. Then someone recognized him.', 'adventure'),
(433, 'He had to win without fighting. He''d never tried that before.', 'adventure'),
(434, 'The wilderness didn''t care about her training. She had to care about it.', 'adventure'),
(435, 'She found the people she was looking for. Getting them out was a different problem.', 'adventure'),
(436, 'The countdown reached zero. Nothing happened. That was the problem.', 'adventure'),
(437, 'He crossed three borders in 24 hours with a name he didn''t own.', 'adventure'),
(438, 'The only way out was through the thing she''d been running from.', 'adventure'),
(439, 'She made it to the other side. Looking back, she understood what she''d crossed.', 'adventure'),
(440, 'He finished the race and realized the race had never been the point.', 'adventure'),
(441, 'The office had been running on the same printer for 22 years. Today it had opinions.', 'humor'),
(442, 'She accidentally applied for a job she wasn''t remotely qualified for and somehow made it to the final round.', 'humor'),
(443, 'He texted the wrong person something deeply personal. The wrong person turned out to be the right one.', 'humor'),
(444, 'The coffee shop got her order wrong every single day in a way that was somehow exactly right.', 'humor'),
(445, 'She agreed to housesit for a neighbor and immediately encountered something no one had warned her about.', 'humor'),
(446, 'He accidentally started a trend he couldn''t stop and didn''t understand.', 'humor'),
(447, 'The autocorrect had been making her life interesting for weeks. Today it went too far.', 'humor'),
(448, 'She showed up to the wrong meeting and accidentally solved a problem that had been open for two years.', 'humor'),
(449, 'He tried to cancel his gym membership and ended up in a philosophical debate.', 'humor'),
(450, 'The customer service call lasted four hours and ended in an unexpected friendship.', 'humor'),
(451, 'She volunteered for something without reading what she was volunteering for.', 'humor'),
(452, 'He rented a van for a simple move and came home with three extra passengers and no explanation.', 'humor'),
(453, 'The wedding toast went off script after the first sentence. It went better that way.', 'humor'),
(454, 'She tried to make a professional impression and immediately tripped over everything.', 'humor'),
(455, 'He followed a recipe exactly and produced something that was technically food.', 'humor'),
(456, 'The group chat had 47 unread messages. She was afraid to open it.', 'humor'),
(457, 'She took a wrong exit and ended up at an event she was somehow expected at.', 'humor'),
(458, 'He tried to explain something simple and it became the most complicated conversation of his life.', 'humor'),
(459, 'The presentation was going well until the slide deck had other ideas.', 'humor'),
(460, 'She tried to be mature about it and lasted eleven minutes.', 'humor'),
(461, 'He bought a plant. It had a personality. This became a problem.', 'humor'),
(462, 'The reunion was going fine until someone brought up the thing everyone agreed not to bring up.', 'humor'),
(463, 'She asked a simple question at the town hall. Two hours later, she was somehow in charge.', 'humor'),
(464, 'He tried to sneak out of a party and accidentally made a grand exit.', 'humor'),
(465, 'The translation app made the negotiation significantly more interesting than planned.', 'humor'),
(466, 'She tried to fix one small thing and discovered it was connected to everything else.', 'humor'),
(467, 'He said "sure, how hard could it be" and immediately found out.', 'humor'),
(468, 'The shortcut through the kitchen at the party became a very long conversation.', 'humor'),
(469, 'She sent an email to the wrong department. The wrong department was surprisingly helpful.', 'humor'),
(470, 'He borrowed something small. It spiraled into the most elaborate chain of events of his life.', 'humor'),
(471, 'Write about a color that doesn''t exist yet.', 'meta'),
(472, 'The last sentence of the story was the first one she wrote. Start from there.', 'meta'),
(473, 'Describe silence in a place that is never quiet.', 'meta'),
(474, 'Write from the perspective of the space between two people who are not speaking.', 'meta'),
(475, 'The thing nobody said out loud was the loudest thing in the room.', 'meta'),
(476, 'Write a story that begins at the end of something and ends at the beginning.', 'meta'),
(477, 'Describe a place by the sounds it makes when no one is there.', 'meta'),
(478, 'The object had passed through forty hands before it reached hers.', 'meta'),
(479, 'Write about a decision that was made before anyone realized it had been made.', 'meta'),
(480, 'The word had lost its meaning. She had to find a new one.', 'meta'),
(481, 'Describe home to someone who has never had one.', 'meta'),
(482, 'He left something behind in every place he''d ever been. Write about the last one.', 'meta'),
(483, 'Write about a moment that lasted longer than it should have.', 'meta'),
(484, 'The feeling didn''t have a name. Write it anyway.', 'meta'),
(485, 'She kept the thing nobody else thought was worth keeping.', 'meta'),
(486, 'Write about what happens in the city after everyone goes to sleep.', 'meta'),
(487, 'The memory arrived without permission and stayed.', 'meta'),
(488, 'He tried to explain why he stayed. He was still explaining.', 'meta'),
(489, 'Write about the space between who someone was and who they became.', 'meta'),
(490, 'The road looked the same in both directions. She picked one anyway.', 'meta'),
(491, 'Write about something ordinary as though you are encountering it for the first time.', 'meta'),
(492, 'The conversation ended before it was finished. Write the rest.', 'meta'),
(493, 'She kept coming back to the same page. Write what was on it.', 'meta'),
(494, 'Write about a goodbye that didn''t know it was one.', 'meta'),
(495, 'He watched something end and tried to hold the last moment still.', 'meta'),
(496, 'Write about what it feels like to wait for something you''re not sure is coming.', 'meta'),
(497, 'She carried something invisible everywhere she went.', 'meta'),
(498, 'Write about the moment just before everything changed.', 'meta'),
(499, 'The answer arrived too late to be useful and too true to ignore.', 'meta'),
(500, 'Write about beginning again.', 'meta'),
(1001, 'Write an apology essay, but you''re a TikToker who got caught stealing a meme...', 'brainrot'),
(1002, 'Explain the plot of Hamlet but entirely in Gen Z slang...', 'brainrot'),
(1003, 'Your aura just dropped to zero in front of your crush. What do you do?', 'brainrot'),
(1004, 'You woke up and realized your entire life was just a 10-hour podcast ad read...', 'brainrot'),
(1005, 'The villain''s evil plan is just to slightly inconvenience everyone''s Wi-Fi connection...', 'brainrot'),
(1006, 'You have to defend yourself in court, but your lawyer only speaks in brainrot...', 'brainrot'),
(1007, 'Your group chat got leaked to the FBI, and now they''re asking questions about...', 'brainrot'),
(1008, 'The Grim Reaper showed up, but you challenged him to a 1v1 on Rust...', 'brainrot'),
(1009, 'You tried to touch grass, but the grass touched you back...', 'brainrot'),
(1010, 'A time traveler arrives from 2050 to warn you about the Great Ratio of 2029...', 'brainrot'),
(1011, 'Your Spotify Wrapped was so unhinged that Spotify sent a wellness check...', 'brainrot'),
(1012, 'Write a dramatic monologue about burning your mouth on a Hot Pocket...', 'brainrot'),
(1013, 'You accidentally liked a picture from 2012, and now the original poster is...', 'brainrot'),
(1014, 'The only way to save the world is to post a cringe dance on TikTok...', 'brainrot'),
(1015, 'Your sleep paralysis demon is actually just a really annoying crypto bro...', 'brainrot'),
(1016, 'You got trapped in an elevator with a guy who won''t stop talking about his podcast...', 'brainrot'),
(1017, 'Explain the economy to a Victorian child using only Fortnite terms...', 'brainrot'),
(1018, 'You discovered the secret to immortality, but it requires spending 5 hours a day on Twitter...', 'brainrot'),
(1019, 'The aliens landed, but they just wanted to know if we had games on our phones...', 'brainrot'),
(1020, 'Write a Yelp review for the concept of ''consciousness''...', 'brainrot'),
(1021, 'You have to explain to your parents why you bought 10,000 V-Bucks using their card...', 'brainrot'),
(1022, 'The protagonist is a sentient vape pen searching for its owner...', 'brainrot'),
(1023, 'You found a cursed artifact that forces you to narrate your life like a YouTuber...', 'brainrot'),
(1024, 'Describe a boss fight, but the boss is your Wi-Fi randomly disconnecting...', 'brainrot'),
(1025, 'You''re trying to hide from a serial killer, but your phone starts playing a loud ad...', 'brainrot'),
(1026, 'The president declared a national emergency because the servers went down...', 'brainrot'),
(1027, 'You entered a cooking competition, but your only ingredient is existential dread...', 'brainrot'),
(1028, 'Write an epic fantasy battle, but the weapons are oversized foam fingers...', 'brainrot'),
(1029, 'You woke up as an NPC in a game, and the main character just quicksaved next to you...', 'brainrot'),
(1030, 'The prophecy foretold of a hero who could read an entire terms and conditions agreement...', 'brainrot');