-- Daily Prompts Migration
INSERT INTO public.daily_prompts (prompt_date, prompt_id, prompt_text, prompt_category) VALUES
('2026-04-22', 'd63', 'Something is broken beyond repair. Write the person who hasn''t accepted that yet.', 'slice'),
('2026-04-23', 'd64', 'Make hope feel dangerous.', 'philosophy'),
('2026-04-24', 'd65', 'Write the moment someone understands something they wish they didn''t.', 'mystery'),
('2026-04-25', 'd66', 'You are narrating your own life to yourself like a stranger would. Be honest.', 'meta'),
('2026-04-26', 'd67', 'Write the conversation that should have happened ten years ago — happening now.', 'romance'),
('2026-04-27', 'd68', 'The person across from you is lying. You know it. You let them finish anyway. Write why.', 'mystery'),
('2026-04-28', 'd69', 'Make ordinary feel like loss.', 'slice'),
('2026-04-29', 'd70', 'Write the internal monologue of someone performing confidence they don''t feel.', 'meta'),
('2026-04-30', 'd92', 'The person you used to be shows up. You have to explain every choice you''ve made since. Go.', 'philosophy'),
('2026-05-01', 'd61', 'Two people are having two completely different arguments using the same words. Write it.', 'romance'),
('2026-05-02', 'd62', 'Write the courage that looks, from the outside, exactly like cowardice.', 'philosophy'),
('2026-05-03', 'd63', 'Something is broken beyond repair. Write the person who hasn''t accepted that yet.', 'slice'),
('2026-05-04', 'd64', 'Make hope feel dangerous.', 'philosophy'),
('2026-05-05', 'd65', 'Write the moment someone understands something they wish they didn''t.', 'mystery'),
('2026-05-06', 'd66', 'You are narrating your own life to yourself like a stranger would. Be honest.', 'meta'),
('2026-05-07', 'd67', 'Write the conversation that should have happened ten years ago — happening now.', 'romance'),
('2026-05-08', 'd68', 'The person across from you is lying. You know it. You let them finish anyway. Write why.', 'mystery'),
('2026-05-09', 'd69', 'Make ordinary feel like loss.', 'slice'),
('2026-05-10', 'd91', 'Write from inside a misunderstanding that both people are too proud to correct.', 'romance'),
('2026-05-11', 'd92', 'The person you used to be shows up. You have to explain every choice you''ve made since. Go.', 'philosophy'),
('2026-05-12', 'd93', 'Write joy that is aware of how temporary it is.', 'romance'),
('2026-05-13', 'd94', 'Make a reader feel homesick for a place they''ve never been.', 'meta'),
('2026-05-14', 'd95', 'Write the moment a person chooses who they love over what they believe — or the other way around.', 'philosophy'),
('2026-05-15', 'd96', 'You are the only one who remembers it happened. Write it before it disappears completely.', 'historical'),
('2026-05-16', 'd97', 'Write the thing that lives between two people who have known each other too long to say it.', 'romance'),
('2026-05-17', 'd98', 'Make the mundane feel like it''s the last time.', 'slice'),
('2026-05-18', 'd99', 'Write the thought a person has in the exact moment their life splits into before and after.', 'philosophy'),
('2026-05-19', 'd100', 'You have three minutes. Write like it matters. Because it does.', 'meta'),
('2026-05-20', 'd22', 'You are the last person to find out about something everyone else already knows.', 'mystery'),
('2026-05-21', 'd23', 'Write fear without using the word or any of its synonyms.', 'horror'),
('2026-05-22', 'd24', 'The meeting is almost over. One person hasn''t said the thing they came to say.', 'slice'),
('2026-05-23', 'd25', 'You have been patient for years. Write the moment you stop.', 'adventure'),
('2026-05-24', 'd26', 'Write the conversation between two people who love each other and are about to ruin it.', 'romance'),
('2026-05-25', 'd27', 'Something small happens. It is the most important thing that has ever happened. Make the reader feel that.', 'slice'),
('2026-05-26', 'd28', 'Write from the perspective of the person in the room no one is paying attention to.', 'slice'),
('2026-05-27', 'd29', 'You are given everything you asked for. Write the problem with that.', 'philosophy'),
('2026-05-28', 'd30', 'Make the reader miss someone they''ve never met.', 'romance'),
('2026-05-29', 'd31', 'Write the moment a person realizes they''ve been the antagonist of someone else''s story.', 'philosophy'),
('2026-05-30', 'd53', 'You have to say something true about yourself to a stranger. Write what you choose and why.', 'slice'),
('2026-05-31', 'd54', 'Write a beginning that feels like an ending.', 'meta'),
('2026-06-01', 'd22', 'You are the last person to find out about something everyone else already knows.', 'mystery'),
('2026-06-02', 'd23', 'Write fear without using the word or any of its synonyms.', 'horror'),
('2026-06-03', 'd24', 'The meeting is almost over. One person hasn''t said the thing they came to say.', 'slice'),
('2026-06-04', 'd25', 'You have been patient for years. Write the moment you stop.', 'adventure'),
('2026-06-05', 'd26', 'Write the conversation between two people who love each other and are about to ruin it.', 'romance'),
('2026-06-06', 'd27', 'Something small happens. It is the most important thing that has ever happened. Make the reader feel that.', 'slice'),
('2026-06-07', 'd28', 'Write from the perspective of the person in the room no one is paying attention to.', 'slice'),
('2026-06-08', 'd29', 'You are given everything you asked for. Write the problem with that.', 'philosophy'),
('2026-06-09', 'd30', 'Make the reader miss someone they''ve never met.', 'romance'),
('2026-06-10', 'd52', 'The door is open. Write why nobody is going through it.', 'mystery'),
('2026-06-11', 'd53', 'You have to say something true about yourself to a stranger. Write what you choose and why.', 'slice'),
('2026-06-12', 'd54', 'Write a beginning that feels like an ending.', 'meta'),
('2026-06-13', 'd55', 'The right thing and the kind thing are different things. Write the choice.', 'philosophy'),
('2026-06-14', 'd56', 'You are trying to describe someone you love to someone who will never meet them. Get it right.', 'romance'),
('2026-06-15', 'd57', 'Write the moment a person realizes they''ve outgrown something they still love.', 'romance'),
('2026-06-16', 'd58', 'Make a reader feel the size of a small room.', 'meta'),
('2026-06-17', 'd59', 'Write from the perspective of the person who always arrives after everything has already happened.', 'slice'),
('2026-06-18', 'd60', 'You are completely alone and it is exactly what you wanted. Write what that actually feels like.', 'slice'),
('2026-06-19', 'd61', 'Two people are having two completely different arguments using the same words. Write it.', 'romance'),
('2026-06-20', 'd83', 'Write a goodbye that pretends to be a hello.', 'romance'),
('2026-06-21', 'd84', 'The rule everyone follows was made by someone who is no longer here. Write the first person to break it.', 'adventure'),
('2026-06-22', 'd85', 'Make silence feel like the loudest thing in the scene.', 'meta'),
('2026-06-23', 'd86', 'Write the moment someone realizes they have been waiting their entire life for something that already happened.', 'slice'),
('2026-06-24', 'd87', 'You are describing someone from memory, years later. Notice what you remember and what you''ve lost.', 'slice'),
('2026-06-25', 'd88', 'Write the version of bravery nobody writes songs about.', 'philosophy'),
('2026-06-26', 'd89', 'Something is about to be said that will change everything. Write every second before it.', 'mystery'),
('2026-06-27', 'd90', 'Make the reader feel the exact weight of a decision that cannot be undone.', 'philosophy'),
('2026-06-28', 'd91', 'Write from inside a misunderstanding that both people are too proud to correct.', 'romance'),
('2026-06-29', 'd92', 'The person you used to be shows up. You have to explain every choice you''ve made since. Go.', 'philosophy'),
('2026-06-30', 'd14', 'You are writing a letter to someone who will never read it. Write it like they will.', 'romance'),
('2026-07-01', 'd83', 'Write a goodbye that pretends to be a hello.', 'romance'),
('2026-07-02', 'd84', 'The rule everyone follows was made by someone who is no longer here. Write the first person to break it.', 'adventure'),
('2026-07-03', 'd85', 'Make silence feel like the loudest thing in the scene.', 'meta'),
('2026-07-04', 'd86', 'Write the moment someone realizes they have been waiting their entire life for something that already happened.', 'slice'),
('2026-07-05', 'd87', 'You are describing someone from memory, years later. Notice what you remember and what you''ve lost.', 'slice'),
('2026-07-06', 'd88', 'Write the version of bravery nobody writes songs about.', 'philosophy'),
('2026-07-07', 'd89', 'Something is about to be said that will change everything. Write every second before it.', 'mystery'),
('2026-07-08', 'd90', 'Make the reader feel the exact weight of a decision that cannot be undone.', 'philosophy'),
('2026-07-09', 'd91', 'Write from inside a misunderstanding that both people are too proud to correct.', 'romance'),
('2026-07-10', 'd13', 'Write the moment someone realizes the thing they''ve been protecting was never theirs to protect.', 'slice'),
('2026-07-11', 'd14', 'You are writing a letter to someone who will never read it. Write it like they will.', 'romance'),
('2026-07-12', 'd15', 'The kindest thing anyone ever did for you was something they didn''t do. Write it.', 'slice'),
('2026-07-13', 'd16', 'Write a chase scene where nobody is running.', 'adventure'),
('2026-07-14', 'd17', 'Two people are saying the same word and meaning completely different things. Write the conversation.', 'slice'),
('2026-07-15', 'd18', 'You are defending something you built that is failing. You still believe in it.', 'philosophy'),
('2026-07-16', 'd19', 'Write the thought that arrives at 3am and won''t leave.', 'horror'),
('2026-07-17', 'd20', 'Make stillness feel more violent than action.', 'meta'),
('2026-07-18', 'd21', 'Write the apology after the apology — the one you mean.', 'romance'),
('2026-07-19', 'd22', 'You are the last person to find out about something everyone else already knows.', 'mystery'),
('2026-07-20', 'd44', 'Write from inside a habit that is slowly becoming a prison.', 'philosophy'),
('2026-07-21', 'd45', 'Someone is about to say the thing that cannot be unsaid. Write the second before.', 'romance'),
('2026-07-22', 'd46', 'You are trying to hold two completely opposite things to be true at the same time. Write the tension.', 'philosophy'),
('2026-07-23', 'd47', 'Write the part of the story nobody tells at the dinner table.', 'slice'),
('2026-07-24', 'd48', 'Make leaving and staying feel equally impossible.', 'romance'),
('2026-07-25', 'd49', 'Write the version of events from the perspective of the person history forgot.', 'historical'),
('2026-07-26', 'd50', 'You are the most qualified person in the room and the least likely to be believed. Write the moment.', 'philosophy'),
('2026-07-27', 'd51', 'Write grief that doesn''t know it''s grief yet.', 'slice'),
('2026-07-28', 'd52', 'The door is open. Write why nobody is going through it.', 'mystery'),
('2026-07-29', 'd53', 'You have to say something true about yourself to a stranger. Write what you choose and why.', 'slice'),
('2026-07-30', 'd75', 'Make a reader feel time stop.', 'meta')
ON CONFLICT (prompt_date) DO UPDATE SET
  prompt_id = EXCLUDED.prompt_id,
  prompt_text = EXCLUDED.prompt_text,
  prompt_category = EXCLUDED.prompt_category;